#!/usr/bin/env bash

# sourced at boot by ~/.xinitrc and most display managers

XDG_CONFIG_HOME="$HOME/.config"
export XDG_CONFIG_HOME

[[ "$PATH" == *"$HOME/bin"* ]] || PATH="$HOME/bin:$PATH"

# FIXME: required for xfce notifications. Must be fixed
/usr/lib/xfce4/notifyd/xfce4-notifyd &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=pkcs11 &
xset dpms 600 900 1200
xset r rate 350 60

~/bin/autostart &
